apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcloud-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcloud-event
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kcloud-event
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: kcloud-event
        image: "{{ .Values.kerberospipeline.event.repository }}:{{ .Values.kerberospipeline.event.tag }}"
        imagePullPolicy: {{ .Values.kerberospipeline.event.pullPolicy }}
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
        env:
        - name: CLOUD_PROVIDER
          value: "{{ .Values.cloudProvider }}"
        - name: QUEUE_SYSTEM
          value: "{{ .Values.queueProvider }}"

        # Database
        - name: MONGODB_HOST
          value: "{{ .Values.mongodb.host }}"
        - name: MONGODB_DATABASE_CREDENTIALS
          value: "{{ .Values.mongodb.adminDatabase }}"
        - name: MONGODB_USERNAME
          value: "{{ .Values.mongodb.username }}"
        - name: MONGODB_PASSWORD
          value: "{{ .Values.mongodb.password }}"

        # Kafka settings
        - name: KAFKA_BROKER
          value: "{{ .Values.kafka.broker }}"
        - name: KAFKA_USERNAME
          value: "{{ .Values.kafka.username }}"
        - name: KAFKA_PASSWORD
          value: "{{ .Values.kafka.password }}"
        - name: KAFKA_MECHANISM
          value: "{{ .Values.kafka.mechanism }}"
        - name: KAFKA_SECURITY
          value: "{{ .Values.kafka.security }}"