apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forwarder
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: forwarder
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: forwarder
          image: "{{ .Values.kerberoshub.forwarder.repository }}:{{ .Values.kerberoshub.forwarder.tag }}"
          imagePullPolicy: {{ .Values.kerberoshub.forwarder.pullPolicy }}
          env:
            # Mongodb
            - name: MONGODB_DATABASE_CLOUD
              value: "Kerberos"
            - name: MONGODB_HOST
              value: "{{ .Values.mongodb.host }}"
            - name: MONGODB_DATABASE_CREDENTIALS
              value: "{{ .Values.mongodb.adminDatabase }}"
            - name: MONGODB_USERNAME
              value: "{{ .Values.mongodb.username }}"
            - name: MONGODB_PASSWORD
              value: "{{ .Values.mongodb.password }}"

            # Mqtt (VERNEMQ)
            - name: MQTT_URI
              value: "{{ .Values.mqtt.host }}"
            - name: MQTT_USERNAME
              value: "{{ .Values.mqtt.username }}"
            - name: MQTT_PASSWORD
              value: "{{ .Values.mqtt.password }}"
