apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-device
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: monitor-device
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: monitor-device
          image: "{{ .Values.kerberoshub.monitor-device.repository }}:{{ .Values.kerberoshub.monitor-device.tag }}"
          imagePullPolicy: {{ .Values.kerberoshub.monitor-device.pullPolicy }}
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
          env:
            - name: CLOUD_PROVIDER
              value: "{{ .Values.cloudProvider }}"
            - name: MAIL_PROVIDER
              value: "{{ .Values.emailProvider }}"

            # Mongodb
            - name: MONGODB_DATABASE_CLOUD
              value: "Kerberos"
            - name: MONGODB_HOST
              value: "{{ .Values.mongodb.host }}"
            - name: MONGODB_DATABASE_CREDENTIALS
              value: "{{ .Values.mongodb.adminDatabase }}"
            - name: MONGODB_USERNAME
              value: "{{ .Values.mongodb.username }}"
            - name: MONGODB_PASSWORD
              value: "{{ .Values.mongodb.password }}"

            # Mail settings
            - name: EMAIL_FROM
              value: "{{ .Values.email.from }}"
            - name: EMAIL_FROM_DISPLAYNAME
              value: "{{ .Values.email.displayName }}"

            # - Plain SMTP
            - name: SMTP_SERVER
              value: "{{ .Values.email.smtp.server }}"
            - name: SMTP_PORT
              value: "{{ .Values.email.smtp.port }}"
            - name: SMTP_USERNAME
              value: "{{ .Values.email.smtp.username }}"
            - name: SMTP_PASSWORD
              value: "{{ .Values.email.smtp.password }}"
            - name: DEVICE_TEMPLATEID
              value: "{{ .Values.email.templates.device }}"
