apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcloud-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kcloud-proxy
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kcloud-proxy
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: kcloud-proxy
          image: "{{ .Values.kerberoshub.proxy.repository }}:{{ .Values.kerberoshub.proxy.tag }}"
          imagePullPolicy: {{ .Values.kerberoshub.proxy.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            # Kerberos Hub API
            - name: KERBEROS_API_CHECK_SUBSCRIPTION
              value: "{{ .Values.kerberoshub.api.schema }}://{{ .Values.kerberoshub.api.url }}/user/has-subscription"
            # Kerberos Vault
            - name: KSTORAGE_URI
              value: "{{ .Values.kerberosvault.uri }}"
            - name: KSTORAGE_ACCESSKEY
              value: "{{ .Values.kerberosvault.accesskey }}"
            - name: KSTORAGE_SECRET
              value: "{{ .Values.kerberosvault.secretkey }}"
            - name: KSTORAGE_PROVIDER
              value: "{{ .Values.kerberosvault.provider }}"
---
apiVersion: v1
kind: Service
metadata:
  name: kcloud-proxy-svc
  labels:
    app: kcloud-proxy-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    app: kcloud-proxy