apiVersion: v1
data:
  .dockerconfigjson: keytoberequested #eyJhdXRocyI6e..wYXNzd29yZCI6Im10RVMtZnk0eHNXeVZmY04yRWJOIiwiYXV0aCI6IlkyVmtjbWxqZG1VNmJYUkZVeTFtZVRSNGMxZDVWbVpqVGpKRllrND0ifX19
kind: Secret
metadata:
  creationTimestamp: "2020-08-30T19:08:30Z"
  name: regcred
  namespace: default
  resourceVersion: "48632275"
  selfLink: /api/v1/namespaces/default/secrets/regcred
  uid: fa3051b8-d819-4b41-a4b6-52b932442c61
type: kubernetes.io/dockerconfigjson