# Default values for kerberoshub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

###########################################################################
# LICENSING information: you will need both a license to run Kerberos Hub,
# and a Registry Key to pull the Kerberos Hub docker images from our private Gitlab repository.
# ----
# Get your license from support@kerberos.io
license: "---ENTER-YOUR-LICENSE-HERE---"
licenseServer:
  url: "https://license.kerberos.io/verify"
  token: "214%Ë†#ddfsf@#3rfdsgl_)23sffeqasSwefDSFNBM" # do not change otherwise Kerberos Hub will not work.
# The registry secret to be able to download all the Docker images.
# Needs to be delivered after license purchase.
imagePullSecrets:
  - name: regcred
  
# Set to 'true' if this is a private deployment.
isPrivate: true

# If you plan a migration or doing maintenance, you can enable readonly.
# This will stop any write process to mongodb or any processing done in the Kerberos Hub pipeline.
readOnly: false

# Which network ingress you are using in your Kubernetes Cluster
ingress: "nginx" # or "traefik"

# A mongodb instance is required to store all the relevant metadata.
mongodb:
  host: mongodb.mongodb.svc.cluster.local
  #host: "mongodb-0.mongodb-headless.mongodb:27017,mongodb-1.mongodb-headless.mongodb:27017"
  adminDatabase: admin
  username: yourusername
  password: "yourpassword"

# A MQTT broker (vernemq) is used to have a bi-directional
# communication between enterprise agents and kerberos hub.
mqtt:
  host: "mqtt.yourdomain.com"
  port: "8443"
  protocol: "wss"
  username: "yourusername"
  password: "yourpassword"

# We are using a pipeline that is orchestrated through Kafka topics
# Events are send back and forth until the processing is done.
queueProvider: "KAFKA"
queueName: "kcloud-event-queue" # This is the topic to which all events are send.
kafka:
  broker: "kafka1.yourdomain.com:9094,kafka2.yourdomain.com:9094"
  username: "yourusername"
  password: "yourpassword"
  mechanism: "PLAIN"
  security: "SASL_PLAINTEXT"

# For allowing WEBRTC a STUN and TURN server is required.
turn:
  host: "turn:turn.yourdomain.com:8443"
  username: "username1"
  password: "password1"

# We have a kerberos vault component installed which contains all the
# recordings. Kerberos vault is queried to retrieve the recordings
# from the appropriate provider.
kerberosvault:
  uri: "https://api.storage.yourdomain.com"
  accesskey: "xxxxx"
  secretkey: "xxxxx"

email:
  provider: "mailgun"
  from: "support@yourdomain.com"
  displayName: "yourdomain.com"
  mailgun:
    domain: "mg.yourdomain.com"
    apikey: "xxxx"
  smtp:
    server: "smtp.yourdomain.com"
    port: "465"
    username: "yourusername"
    password: "yourpassword"
  templates:
    welcome: "welcome"
    welcomeTitle: "Welcome to Kerberos Hub"
    activate: "activate"
    activateTitle: "Wonderful! Your Kerberos Hub is now active"
    forgot: "forgot"
    forgotTitle: "Password reset Kerberos Hub. You forgot your password"
    detection: "detection"
    disabled: "disabled"
    highupload: "highupload"
    device: "device"

# Following are all the different deployments needed to make
# Kerberos hub properly working.

kerberoshub:
  api:
    repository: registry.gitlab.com/kerberos-io/kerberos-cloud-api
    pullPolicy: IfNotPresent
    tag: "1.0.473558360"
    replicas: 2

    jwtSecret: "13O587879874656oiyiuoyiu" # change to a random value, this is for generating JWT tokens.
    schema: "https"
    url: "api.yourdomain.com"

    # Admin API's are made available for automation of Kerberos Hub.
    # To access those API's (e.g. creation of owner users), an API key needs to be provided.
    apiKey: "a-random-admin-api-key"

    tls:
      - hosts:
          - "api.yourdomain.com"
        secretName: kerberoshub-api
      - hosts:
          - "admin.api.yourdomain.com"
        secretName: kerberoshub-admin
    language: "english"
    fallbackLanguage: "english"
    aws: # Legacy (reseller) it is possible to link to AWS S3 and IAM (however Kerberos Vault is now the recommended option).
      region: "xxx"
      bucket: "xxx"
      accessKey: "xxx"
      secretKey: "xxx"
    stripe: # We use stripe for billing, so it's possible to resell Kerberos Hub if agreed.
      privateKey: "xxx"
    slack: # Slack is used in the api, to send logs to a specific Slack channel.
      enabled: "true"
      hook: "yourslackhook" # https://hooks.slack.com/services/T08Q2Q9V5/xxKT/JALxxAk26bHtuqTfZ
      username: "Kerberos Hub" # The slack username
    elasticsearch: # Logs of the kerberos hub will be send to an elastic search cluster.
      enabled: "true"
      protocol: "http"
      host: "yourelasticsearchinstance.com"
      port: "9200"
      index: "kerberos-cloud"
      username: ""
      password: ""
    sso: # OIDC settings for allowing SSO.
      issuer: "" #"https://accounts.google.com"
      clientId: "" # 4294xxxxsk4no3.apps.googleusercontent.com"
      clientSecret: "" # UksvZ-QKGdB1W2mOu5l_Jg3R"
      redirectUrl: "/sso/response"
  frontend:
    repository: registry.gitlab.com/kerberos-io/kerberos-cloud-ng
    pullPolicy: IfNotPresent
    tag: "1.0.473710182"
    replicas: 2

    schema: "https"
    url: "yourdomain.com"
    tls:
      - hosts:
          - "yourdomain.com"
        secretName: kerberoshub
    ssoDomain: "@yourdomain.com"
    mixpanel: # We can keep track logging in Mixpanel as well
      apikey: "xxx"
    sentry: # We can trace errors in Sentry
      url: "https://xxx@sentry.io/xxx"
    stripe: # We use stripe for billing, so it's possible to resell Kerberos Hub if agreed.
      publicKey: ""
    googlemaps: # Google maps is used inside the application to visualise cameras and sites.
      apikey: "xxxx"
    zendesk: # We can use different support tools, for now we use Zendesk but others can be integrated
      url: "yourdomain.zendesk.com"

    # Page title (browser)
    title: "Kerberos Hub - Video surveillance as it should be"

    # You can style Kerberos hub as you wish.
    # 1. we do the styling on our side and bake it in the Docker image (change the logo attribute to your company name)
    # 2. you bring your own logo (set logo to 'custom'), and mount the css file and favicons.
    # we will need to include your logo in the Docker image, so please reach out to us.
    logo: "custom"
    # Custom layout: override css
    # By providing a style.css file in the custom folder
    # this file will override any css styling.
    #volumeMounts:
    #  - name: custom-layout
    #    mountPath: /usr/share/nginx/html/assets/custom
    #  - name: custom-favicon
    #    mountPath: /usr/share/nginx/html/assets/favicon
    #volumes:
    #  - name: custom-layout
    #    persistentVolumeClaim:
    #      claimName: custom-layout-claim
    #  - name: custom-favicon
    #    persistentVolumeClaim:
    #      claimName: custom-favicon-claim

    # By specifying the below environments variables, you can tweak the
    # headings and paragraphs of Kerberos Hub.
    
    # Login page
    loginDescription: ""
    loginCopyright: ""
    
    # Dashboard page
    dashboardTitle: ""
    dashboardSubTitle: ""
    
    # Latest events page
    latestEventsTitle: ""
    latestEventsSubTitle: ""
    
    # Livestream/view page
    livestreamTitle: ""
    livestreamSubTitle: ""
    
    # Media page
    mediaTitle: ""
    mediaSubTitle: ""
   
    # Optional - for custom page.
    cpuUsageDescription: ""
    framesPerSecondDescription: ""
    mlaUtilizationDescription: ""
    objectsDetectedDescription: ""

  cleanup:
    repository: registry.gitlab.com/kerberos-io/kerberos-cloud-cleanup
    pullPolicy: IfNotPresent
    tag: "1.0.1807619890"
  forwarder:
    repository: registry.gitlab.com/kerberos-io/vault-forwarder
    pullPolicy: IfNotPresent
    tag: "1.0.1613962421"
  monitordevice:
    repository: registry.gitlab.com/kerberos-io/kerberos-monitor-device
    pullPolicy: IfNotPresent
    tag: "1.0.1919848645"
  reactivate:
    repository: registry.gitlab.com/kerberos-io/kerberos-reactivate
    pullPolicy: IfNotPresent
    tag: "1.0.2041756405"
  # This proxy is legacy for the old agent, will be migrated in the new Hub API.
  proxy:
    repository: registry.gitlab.com/kerberos-io/kerberos-cloud-proxy
    pullPolicy: IfNotPresent
    tag: "1.0.2041838648"

kerberospipeline:
  event:
    repository: registry.gitlab.com/kerberos-io/kcloud-event-queue
    pullPolicy: IfNotPresent
    tag: "1.0.766190255"
  monitor:
    repository: registry.gitlab.com/kerberos-io/kcloud-monitor-queue
    pullPolicy: IfNotPresent
    tag: "1.0.2040627860"
  sequence:
    repository: registry.gitlab.com/kerberos-io/kcloud-sequence-queue
    pullPolicy: IfNotPresent
    tag: "1.0.1613913235"
  throttler:
    repository: registry.gitlab.com/kerberos-io/kcloud-throttler-queue
    pullPolicy: IfNotPresent
    tag: "1.0.1613950978"
  notify:
    repository: registry.gitlab.com/kerberos-io/kcloud-notify-queue
    pullPolicy: IfNotPresent
    tag: "1.0.1921248319"
  notifyTest:
    repository: registry.gitlab.com/kerberos-io/kcloud-notify-test-queue
    pullPolicy: IfNotPresent
    tag: "1.0.1917516775"
  analysis:
    repository: registry.gitlab.com/kerberos-io/kcloud-analysis-queue
    pullPolicy: IfNotPresent
    tag: "1.0.1613937799"
  dominantColor:
    repository: registry.gitlab.com/kerberos-io/kcloud-dominantcolor-queue
    pullPolicy: IfNotPresent
    tag: "1.0.906298340"
  thumbnail:
    repository: registry.gitlab.com/kerberos-io/kcloud-thumbnail-queue
    pullPolicy: IfNotPresent
    tag: "1.0.1294067330"
  counting:
    repository: registry.gitlab.com/kerberos-io/kcloud-counting-queue
    pullPolicy: IfNotPresent
    tag: "1.0.911063420"
