---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
type: Opaque
stringData:
  api-key: your apikey #e.g. 47a929f077xxxxxx583cb21
---
apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: vernemq-letsencrypt-iss
spec:
  acme:
    email: info@cedricve.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: vernemq-letsencrypt-iss-key
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: your@email.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
